"""ai_model_and_prompt_registry

Revision ID: 190bd9770a51
Revises: 31f521a1e46c
Create Date: 2026-10-06 12:28:10.255047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '190bd9770a51'
down_revision: Union[str, Sequence[str], None] = '31f521a1e46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version_label', sa.String(length=80), server_default='default', nullable=False),
    sa.Column('family', sa.String(length=80), nullable=True),
    sa.Column('modality', sa.String(length=40), nullable=False),
    sa.Column('quantization', sa.String(length=40), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('serving_endpoint', sa.String(length=255), nullable=False),
    sa.Column('model_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version_label', name='uq_model_name_version')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'version', name='uq_prompt_key_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_versions')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
